config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :nutrition_plans do
    member do
      get 'show_dishes'
      post 'add_dishes'
      delete 'remove_dish'
    end
  end

  root 'nutrition_plans#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :calories, presence: true, positive: true
  validates :protein, presence: true, positive: true
  validates :carbohydrates, presence: true, positive: true
  validates :fat, presence: true, positive: true

  has_many :dishes_nutrition_plans
  has_many :nutrition_plans, through: :dishes_nutrition_plans
end

app/models/dishes_nutrition_plan.rb
class DishesNutritionPlan < ActiveRecord::Base
  belongs_to :dish
  belongs_to :nutrition_plan
end

app/models/nutrition_plan.rb
class NutritionPlan < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :dishes_nutrition_plans
  has_many :dishes, through: :dishes_nutrition_plans

  def total_nutritional_value
    result = { calories: 0, protein: 0, carbohydrates: 0, fat: 0 }

    dishes.each do |dish|
      result[:calories] += dish.calories
      result[:protein] += dish.protein
      result[:carbohydrates] += dish.carbohydrates
      result[:fat] += dish.fat
    end

    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  def index
    @dishes = Dish.all
  end

  def show
  end

  def new
    @dish = Dish.new
  end

  def edit
  end

  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      redirect_to @dish, notice: 'Dish was successfully created.'
    else
      render :new
    end
  end

  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Dish was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @dish.destroy

    redirect_to dishes_url, notice: 'Dish was successfully destroyed.'
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(
      :name,
      :calories,
      :protein,
      :carbohydrates,
      :fat
    )
  end
end

app/controllers/nutrition_plans_controller.rb
class NutritionPlansController < ApplicationController
  before_action :set_nutrition_plan, except: [:index, :new, :create]

  def index
    @nutrition_plans = NutritionPlan.all
  end

  def show
  end

  def new
    @nutrition_plan = NutritionPlan.new
  end

  def edit
  end

  def create
    @nutrition_plan = NutritionPlan.new(nutrition_plan_params)

    if @nutrition_plan.save
      redirect_to(
        @nutrition_plan,
        notice: 'Nutrition plan was successfully created.'
      )
    else
      render :new
    end
  end

  def update
    if @nutrition_plan.update(nutrition_plan_params)
      redirect_to(
        @nutrition_plan,
        notice: 'Nutrition plan was successfully updated.'
      )
    else
      render :edit
    end
  end

  def destroy
    @nutrition_plan.destroy

    redirect_to(
      nutrition_plans_url,
      notice: 'Nutrition plan was successfully destroyed.'
    )
  end

  def show_dishes
    @dishes = Dish.all
  end

  def add_dishes
    dishes_ids = params.require(:nutrition_plan)[:dish_ids].reject(&:empty?)
    @nutrition_plan.dishes = Dish.find(dishes_ids)

    redirect_to(
        @nutrition_plan,
        notice: 'Dishes were added successfully.'
      )
  end

  def remove_dish
    @nutrition_plan.dishes.delete(params.require(:dish))

    redirect_to(
      nutrition_plan_path(@nutrition_plan),
      notice: 'Dish was successfully removed.'
    )
  end

  private

  def set_nutrition_plan
    @nutrition_plan = NutritionPlan.find(params[:id])
  end

  def nutrition_plan_params
    params.require(:nutrition_plan).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dishes/_dish.html.erb
<%= simple_form_for(dish) do |f| %>
  <%= f.input :name %>
  <%= f.input :calories %>
  <%= f.input :protein %>
  <%= f.input :carbohydrates %>
  <%= f.input :fat %>

  <%= f.button :submit %>
<% end %>

app/views/dishes/edit.html.erb
<h1>Edit dish</h1>

<%= render @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Dish list</h1>

<% unless @dishes.blank? %>
  <% @dishes.each do |dish| %>
    <div>
      <%= dish.name %>
      <%= link_to 'Show', dish %>
      <%= link_to 'Edit', edit_dish_path(dish) %>
      <%= link_to 'Destroy', dish, method: :delete, data: { confirm:
        'Are you sure? '} %>
    </div>
  <% end %>
<% else %>
  <div>There are no dishes</div>
<% end %>

<%= link_to 'New dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<h1><%= @dish.name %></h1>

<div><%= notice %></div>

<div>
  <%= @dish.calories %>
  <%= @dish.protein %>
  <%= @dish.carbohydrates %>
  <%= @dish.fat %>
</div>

<%= link_to 'Edit', edit_dish_path(@dish) %>
<%= link_to 'Back', dishes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NutritionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nutrition_plans/_nutrition_plan.html.erb
<%= simple_form_for(nutrition_plan) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/nutrition_plans/edit.html.erb
<h1>Edit nutrition plan</h1>

<%= render @nutrition_plan %>

<%= link_to 'Back', nutrition_plans_path %>

app/views/nutrition_plans/index.html.erb
<h1>Nutrition plans</h1>

<% unless @nutrition_plans.blank? %>
  <% @nutrition_plans.each do |nutrition_plan| %>
    <div>
      <%= nutrition_plan.name %>
      <%= link_to 'Show', nutrition_plan %>
      <%= link_to 'Edit', edit_nutrition_plan_path(nutrition_plan) %>
      <%= link_to 'Destroy', nutrition_plan, method: :delete, data: { confirm:
        'Are you sure? '} %>
    </div>
  <% end %>
<% else %>
  <div>There are no nutrition plans</div>
<% end %>

<%= link_to 'New nutrition plan', new_nutrition_plan_path %>
<%= link_to 'Dishes', dishes_path %>

app/views/nutrition_plans/new.html.erb
<h1>New nutrition plan</h1>

<%= render @nutrition_plan %>

<%= link_to 'Back', nutrition_plans_path %>

app/views/nutrition_plans/show.html.erb
<h1><%= @nutrition_plan.name %></h1>

<div><%= notice %></div>

<div>
  <% if @nutrition_plan.dishes.blank? %>
    <div>No dishes yet</div>
  <% else %>
    <ul>
    <% @nutrition_plan.dishes.each do |dish| %>
      <li>
        <%= dish.name %>
        <%= link_to(
          'Remove',
          remove_dish_nutrition_plan_path(@nutrition_plan, dish: dish),
          method: :delete,
          data: { confirm: 'Are you sure? '}
        ) %>
      </li>
    <% end %>
    </ul>
    <div>
      <% total = @nutrition_plan.total_nutritional_value %>
      Total:
      <ul>
        <li>Calories: <%= total[:calories] %></li>
        <li>Protein: <%= total[:protein] %></li>
        <li>Carbohydrates: <%= total[:carbohydrates] %></li>
        <li>Fat: <%= total[:fat] %></li>
      </ul>
    </div>
  <% end %>
</div>

<%= link_to 'Add dish', show_dishes_nutrition_plan_path(@nutrition_plan) %>
<%= link_to 'Edit', edit_nutrition_plan_path(@nutrition_plan) %>
<%= link_to 'Back', nutrition_plans_path %>

app/views/nutrition_plans/show_dishes.html.erb
<h1>Add dish to <%= @nutrition_plan.name %></h1>

  <%= simple_form_for(
    @nutrition_plan,
    url: add_dishes_nutrition_plan_path(@nutrition_plan),
    method: :post
  ) do |f| %>
    <%= f.association :dishes, as: :check_boxes %>
    <%= f.button :submit %>
  <% end %>

<%= link_to 'Back', nutrition_plans_path %>